# application.properties가 없을 경우 application.yml 파일을 스캔해 어플리케이션 설정
# chapter6 설정과 비교
springtour:
  domain:
    name: http://springtour.io
  kafka:
    bootstrap-servers: # 리스트 형태로 선언할 때
      - 10.1.1.100
      - 10.1.1.101
      - 10.1.1.102
  topic:
    checkout: springtour-hotel-event-checkout
    reservation: springtour-hotel-event-reservation
  ack-level: 1